name: CI .NET

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Dotnet Publish
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          key: ${{secrets.KEY}}
          passphrase: ${{secrets.PASSPHRASE}}
          script: |
            cd /git_pull
            git reset --hard origin/main
            git pull origin main
            cd /git_pull/UI
            dotnet restore
            dotnet test --no-build --verbosity normal
            dotnet publish -r linux-x64
            rm -rf /publish/*
            mv /git_pull/UI/bin/Debug/netcoreapp3.1/linux-x64/publish/* /publish/
            systemctl restart perdecim.service