name: CI .NET

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Dotnet Publish
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          #password: ${{ secrets.PASSWORD }}
          port: ${{secrets.PORT}}
          key: ${{secrets.KEY}}
          passphrase: ${{secrets.PASSPHRASE}}
          script: whoami
