name: CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Sefa Karakaya"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1
      - name: Dotnet Publish
        run: dotnet publish
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            sudo cp -r /home/runner/work/perdecim/perdecim/UI/bin/Debug/netcoreapp3.1/publish /home/skarakaya/var/html/www/perdecim/
            sudo systemctl restart perdecim.service
